name: "docker"
on:
  push:
    branches: [main,dev]

jobs:
  upload_docker_images:
    runs-on: ubuntu-latest
    steps:
    -uses: actions/checkout@v3
    - name: Log in to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build base docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai6_base:base -f ./dependency/Dockerfile/Dockerfile_base .
    - name: Push base image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai6_base:base


    - name: Build cpp_compile docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai6_cpp:latest -f ./dependency/Dockerfile/Dockerfile_cpp .
    - name: Push cpp_compile image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai6_cpp:latest

    - name: Build run docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai6_run:latest -f ./dependency/Dockerfile/Dockerfile_run .
    - name: Push run image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai6_run:latest
 
